steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - OrderCloudFunction
      - --source=.
      - --trigger-http
      - --runtime=java11
